# Generated by Django 4.0.6 on 2022-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=140)),
                ('module_title', models.CharField(max_length=140)),
                ('module_abbrev', models.CharField(max_length=140)),
                ('module_type', models.CharField(max_length=140)),
                ('credit_points', models.IntegerField()),
                ('language', models.CharField(max_length=140)),
                ('duration_of_module', models.IntegerField()),
                ('recommended_semester', models.IntegerField()),
                ('frequency', models.CharField(max_length=140)),
                ('assessment_methods', models.CharField(max_length=140)),
                ('workload', models.IntegerField()),
                ('lecture', models.IntegerField()),
                ('seminar', models.IntegerField()),
                ('practical', models.IntegerField()),
                ('excersice', models.IntegerField()),
                ('self_study', models.IntegerField()),
                ('status', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('po', models.CharField(max_length=140)),
                ('furtherInformation', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['recommended_semester'],
            },
        ),
    ]
