# Generated by Django 4.0.6 on 2022-09-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='location',
            new_name='coordinators',
        ),
        migrations.RemoveField(
            model_name='course',
            name='excersice',
        ),
        migrations.RemoveField(
            model_name='course',
            name='furtherInformation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='po',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seminar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
