# Generated by Django 4.0.6 on 2022-09-01 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_location_course_coordinators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excersice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='course',
            name='practical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='required_prerequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default='', size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='self_study',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='seminar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='assessment_methods',
            field=models.CharField(default='', max_length=140),
        ),
    ]
