# Generated by Django 4.0.6 on 2022-09-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_excersice_course_lecture_course_lecturers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='required_prerequisites',
        ),
    ]
