# Generated by Django 4.0.6 on 2022-09-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_coordinators_course_coordinators_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='recommended_prerequisites',
            new_name='recommended_prerequisites_list',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='required_prerequisites',
            new_name='required_prerequisites_list',
        ),
    ]
