# Generated by Django 4.0.6 on 2022-09-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_lecturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.TextField(default=''),
        ),
    ]
