# Generated by Django 4.0.6 on 2022-09-01 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='excersice',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seminar',
        ),
        migrations.AlterField(
            model_name='course',
            name='coordinators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=140, null=True), blank=True, size=None),
        ),
    ]
