# Generated by Django 4.0.6 on 2022-09-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_linebreak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('recommended_semester', 'module_title')},
        ),
    ]
