# Generated by Django 4.0.6 on 2022-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_excersice_remove_course_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=140),
        ),
    ]
