# Generated by Django 4.0.6 on 2022-09-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_lecturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_prerequisites',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_prerequisites',
            field=models.TextField(default='', null=True),
        ),
    ]
