# Generated by Django 4.0.6 on 2022-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_lecturers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinators',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_prerequisites',
            field=models.JSONField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_prerequisites',
            field=models.JSONField(default=''),
        ),
    ]
