# Generated by Django 4.0.6 on 2022-09-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
    ]
