# Generated by Django 4.0.6 on 2022-09-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_coordinators_remove_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_methods',
        ),
    ]
