# Generated by Django 4.0.6 on 2022-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_assessment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
