# Generated by Django 4.0.6 on 2022-09-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
    ]
