# Generated by Django 4.0.6 on 2022-09-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_course_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=140),
        ),
    ]
