# Generated by Django 4.0.6 on 2022-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='coordinators',
            field=models.TextField(null=True),
        ),
    ]
