# Generated by Django 4.0.6 on 2022-09-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_options_course_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.TextField(null=True),
        ),
    ]
