# Generated by Django 4.0.6 on 2022-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_assessment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(default=''),
        ),
    ]
