# Generated by Django 4.0.6 on 2022-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_course_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(),
        ),
    ]
