# Generated by Django 4.0.6 on 2022-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_course_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
