# Generated by Django 4.0.6 on 2022-09-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_course_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
    ]
