# Generated by Django 4.0.6 on 2022-09-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_remove_course_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='course',
            name='po',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='course',
            name='practical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='self_study',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='seminar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='', max_length=140),
        ),
    ]
