# Generated by Django 4.0.6 on 2022-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_course_excercise_course_lecture_course_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='furtherInformation',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
