# Generated by Django 4.0.6 on 2022-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_course_furtherinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_prerequisites',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='required_prerequisites',
            field=models.TextField(null=True),
        ),
    ]
