# Generated by Django 4.0.6 on 2022-09-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='furtherInformation',
            new_name='further_information',
        ),
    ]
