# Generated by Django 4.0.6 on 2022-09-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_furtherinformation_course_further_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coordinators',
            new_name='coordinators_list',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='lecturers',
            new_name='lecturers_list',
        ),
    ]
