# Generated by Django 4.0.6 on 2022-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_recommended_prerequisites_course_recommended_prerequisites_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='po',
        ),
        migrations.AddField(
            model_name='course',
            name='po_list',
            field=models.JSONField(default=''),
        ),
    ]
