# Generated by Django 4.0.6 on 2022-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_po_course_po_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='linebreak',
            field=models.CharField(default='', max_length=140),
        ),
    ]
